#ifndef ACTIONS_H
#define ACTIONS_H

// #include "headers.h"

typedef enum Actions {
    A_DONOTHING,
    A_SCOPEDECREASE,
    A_SELECTCHAR,
    A_SELECTALL,
    A_SELECTALLATCURSORTOWARDSDIR,
    A_MOVECURSOR,
    A_MOVECURSORBYTOKEN,
    A_MOVECURSORTOSTART,
    A_MOVECURSORTOEND,
    A_LOADTIMES,
    A_SAVETIMES,
    A_EXPORTTIMES,
    A_CLEARTIMES,
    A_DESELECT_OR_UNDO_BACKOUT,
    A_OVERWRITE_UPDATESCORE,
    A_NAVIGATETONEXTCELL,
    A_COPY,
    A_CUT,
    A_PASTE,
    A_DELETE,
    A_DELETECELLTEXT,
    A_DELETECELLTEXTANDENTERINTO,
    A_DELETESELECTION,
    A_DELETECHAR,
    A_NAVIGATELEFT,
    A_NAVIGATERIGHT,
    A_NAVIGATEUP,
    A_NAVIGATEDOWN,
    A_SWAPVETOCOLOR,

    ACTION_COUNT
} Actions;

extern Actions ActionTable[3][KEY_COMBO_COUNT];
extern void (*Action[ACTION_COUNT])();

#endif